version: ~> 1.0

env: 
   global:
      - secure: "DsaNbsliWLcxAIb+FnRvw6zA1qE9FUkSq3rN4oTp4ioCu67/q6La6LCbusI1cu5swt0F2mfD+MiCF1/3vkUqEz7bgu330ndFfeouzSnDhdr5/NlTb798XIYQz6RmXNwy9hz0Eu7LisJZtOAR4hnqt4V1Cj1rx42IzBPvKlts/Rp92h1APARKy00f5sPNBsUEAhnVeRpKEO9S5WVILJxdtE0dGnd9k/Uj6+hhlqYJ69S+BxQ4qiMiXOTcAj0HTkdj/6JZL5aTDLEfciecSWcCeSdDTkd2nBSLErgvZvQ1OEHaHgENkkld7IYeh56riTi77d/7EPTcKMTdQoia3isJYjXAZ7R1+OzsqOvNM1UfGpoxInfuzKFCgiLdYMHHe5IgTKSR3u7EzG641cGH2SosVOmH66x5Cri+cKB08tyZGuCUSky9WJmpuYt5ouHy5ChaaLwLjSEP70J+HJRPMKgL0cSi6A7QWx9SyKdIp063nJV7r5zuMPFQEcxWgIaCHZKTWcRyKT94k8KJEkkxmprdtKYYJGdeinXEcIY7cqd9FQdwH6NehkrOC/nrphyeKdTOaQaHQDxQzJwGInYw2aFTlxndqBVqpkjEViRqKNZ0wZBVVSlG2yo60RGEpiHd7kGwQ5daDRvOeHmD6wiQz5viK5e46zaF0scZ7hn6NEPC8QA="
      
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="pcdsutils"

    # The name of the conda package
    - CONDA_PACKAGE="pcdsutils"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

jobs:
  allow_failures:
    - name: "Python 3.6 - PIP"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
